ruoyi:
    # 文件路径 示例（ Windows配置D:/ruoyi/uploadPath，Linux配置 /home/ruoyi/uploadPath）
    profile: /app/customer-service/file
server:
    # 服务器的HTTP端口，默认为8080
    port: 8088
# 数据源配置
spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        druid:
            # 主库数据源
            master:
                url: jdbc:mysql://localhost:3306/pi?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
                username: root
                password: 1qaz@WSX3edc
            # 从库数据源
            slave:
                # 从数据源开关/默认关闭
                enabled: false
                url: 
                username: 
                password: 

    data:
      mongodb:
          host: 127.0.0.1
          port: 27017
          database: admin
          username: admin
          password: 1qaz@WSX3edc
      redis:
          # 地址
          host: 127.0.0.1
          # 端口，默认为6379
          port: 16379
          # 数据库索引（因为向量检索不区分rdis数据库序号，所以只能存储在0下面）
          database: 0
          # 密码
          password: 7ujm*IK<
          # 连接超时时间
          timeout: 10s
# 日志配置
logging:
    level:
        com.ruoyi: info
    file:
        path: /app/logs/customer-service
# SpringDoc OpenAPI 配置
springdoc:
    api-docs:
        enabled: true
    swagger-ui:
        enabled: true
#向量数据库配置
langchain4j:
    community:
        redis:
            # 是否启用 ，默认true
            enabled: true
            # 地址
            host: 127.0.0.1
            # 端口，默认为6379
            port: 16379
            # redis没有用户，但注册时如果带了密码就必须带用户名称，这里给默认用户
            user: default
            # 密码
            password: 7ujm*IK<
            # 缓存前缀
            prefix: "knowledge:"
            # 向量数据库索引
            index-name: ai-embeddings
            dimension: 1024  # 与 embedding-model 维度匹配 text-embedding-v3是1024
            metadata-keys:
                - $.kbId
                - $.docId
                - $.userId
                - $.tenant
                - $.index
                - $.timestamp
